# site
title: Dr Mikes Tips
name: Dr Mike Gardner
port: 4104
profilepic: "assets/media/albatros.jpg"
author:
  name: Dr Mike Gardner
  email: mike.gardner@nottingham.ac.uk

# Dependencies
markdown:         kramdown
highlighter:      rouge

permalink: pretty

exclude: ["README.md"] # files to exclude

disqus: dbyll
google_analytics: dbyll


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Dr Mikes Tips

description: Stylish Jekyll Theme


rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:
